Repository DeveloperAcademy-POSTECH/2025-C4-M15-Chalkak, pull requests merged in 2025-07, with the labels that each got.

#17 ✨ [Feat] 기울기 & 높이 인식 및 피드백 구현
  Chalkak/Core/Guide/Height/CameraHeightManager.swift
  Chalkak/Core/Guide/Height/HeightFeedbackView.swift
  Chalkak/Core/Guide/Height/HeightMeasurementARView.swift
  Chalkak/Core/Guide/Tilt/CameraTiltManager.swift
  Chalkak/Core/Guide/Tilt/TiltDataCollector.swift
  Chalkak/Core/Guide/Tilt/TiltFeedbackView.swift
  Chalkak/Model/Tilt.swift
Labels: feature

#39 ✨ [Feat] 클립 여러 개 한 개의 영상으로 합치기
  Chalkak.xcodeproj/project.pbxproj
  Chalkak/Core/VideoEditor/VideoLoader.swift
  Chalkak/Core/VideoEditor/VideoManager.swift
  Chalkak/Core/VideoEditor/VideoMerger.swift
  Chalkak/Presentation/ClipEdit/ClipEditView.swift
Labels: feature

#67 ✨ [Feat] Tilt 피드백 기능 플로우에 반영하기
  Chalkak/App/ChalkakApp.swift
  Chalkak/Common/Util/Enum/Path.swift
  Chalkak/Core/Guide/Tilt/TiltDataCollector.swift
  Chalkak/Data/Model/Tilt.swift
  Chalkak/Data/SwiftDataManager.swift
  Chalkak/Presentation/Camera/CameraView.swift
  Chalkak/Presentation/Camera/CameraViewModel.swift
  Chalkak/Presentation/ClipEdit/ClipEditView.swift
  Chalkak/Presentation/ClipEdit/ClipEditViewModel.swift
  Chalkak/Presentation/Guide/Distance/BoundingBoxView.swift
  Chalkak/Presentation/Guide/Distance/BoundingBoxViewModel.swift
  Chalkak/Presentation/Guide/Overlay/OverlayView.swift
  Chalkak/Presentation/Guide/Overlay/OverlayViewModel.swift
Labels: enhancement, feature

#98 💄 [Style] #90 CameraView Hi-Fi 적용
  Chalkak/Presentation/Camera/CameraView.swift
  Chalkak/Presentation/Camera/CameraViewModel.swift
  Chalkak/Presentation/Camera/Preview/CameraPreviewView.swift
  Chalkak/Presentation/Camera/SubViews/CameraBaseFeatureSelectView.swift
  Chalkak/Presentation/Camera/SubViews/CameraDefaultTopControlView.swift
  Chalkak/Presentation/Camera/SubViews/CameraRecordView.swift
  Chalkak/Presentation/Camera/SubViews/HorizontalLevelIndicatorView.swift
  Chalkak/Presentation/Camera/SubViews/RecordButton.swift
  Chalkak/Presentation/Camera/SubViews/TimerOptionSelectView.swift
Labels: enhancement
